/****** actions *****/
export const LOCALE_CHANGE = 'LOCALE_CHANGE'
export const MSG_PROMPT = 'MSG_PROMPT'
export const MSG_PROMPT_SPIN = 'MSG_PROMPT_SPIN'
export const ACCOUNT_CHANGE = 'ACCOUNT_CHANGE'
export const MSG_PROGRESS = 'MSG_PROGRESS'
export const PAGE_STATUS = 'PAGE_STATUS'
export const CHANGE_PWD_STATUS = 'CHANGE_PWD_STATUS'
export const CHANGE_PWD_STYLE = 'CHANGE_PWD_STYLE'
export const CHANGE_TAB_KEYS = 'CHANGE_TAB_KEYS'
export const UPDATE_APPLY_BUTTON = 'UPDATE_APPLY_BUTTON'
export const HASH_CHANGE = 'HASH_CHANGE'
export const CUR_MENU_CHANGE = 'CUR_MENU_CHANGE'
export const TAB_KEY_CHANGE = 'TAB_KEY_CHANGE'
export const HEIGHT_CHANGE = 'HEIGHT_CHANGE'
export const ENTER_SAVING = 'ENTER_SAVING'
export const UPLOAD_STATUS = 'UPLOAD_STATUS'
export const SET_MAX_ACCT_NUM = 'SET_MAX_ACCT_NUM'
/****** requests ******/

// global
export const REQUEST_USER_TYPE = 'REQUEST_USER_TYPE'
export const REQUEST_GET_MENU = 'REQUEST_GET_MENU'
export const REQUEST_GET_VENDOR = 'REQUEST_GET_VENDOR'
export const REQUEST_GET_ITEM_VALUE = 'REQUEST_GET_ITEM_VALUE'
export const REQUEST_GET_PRODUCT = 'REQUEST_GET_PRODUCT'
export const REQUEST_GET_PRODUCTSTR = 'REQUEST_GET_PRODUCTSTR'
export const REQUEST_GET_FXOEXIT = 'REQUEST_GET_FXOEXIT'
export const REQUEST_GET_COLOREXIT = 'REQUEST_GET_COLOREXIT'

// status
export const REQUEST_GET_ACCT_STATUS = 'REQUEST_GET_ACCT_STATUS'
export const REQUEST_GET_NETWORK_STATUS = 'REQUEST_GET_NETWORK_STATUS'
export const REQUEST_GET_SYSTEM_UPTIME = 'REQUEST_GET_SYSTEM_UPTIME'
export const REQUEST_GET_SYSTEM_PRODUCT = 'REQUEST_GET_SYSTEM_PRODUCT'
export const REQUEST_GET_SYSTEM_PN = 'REQUEST_GET_SYSTEM_PN'
export const REQUEST_GET_STORAGE_INFO = 'REQUEST_GET_STORAGE_INFO'

// account
export const GET_IPVT_EXIST = 'GET_IPVT_EXIST'

// callset


// sysset
export const REQUEST_GET_READSHOWIP_STATE = 'REQUEST_GET_READSHOWIP_STATE'
export const REQUEST_GET_TIMEZONE_VALUES = 'REQUEST_GET_TIMEZONE_VALUES'
export const REQUEST_GET_LANGUAGES_VALUES = 'REQUEST_GET_LANGUAGES_VALUES'
export const REQUEST_GET_VERI_CERT = 'REQUEST_GET_VERI_CERT'
export const REQUEST_GET_WIFI_RESULT = 'REQUEST_GET_WIFI_RESULT'

// maintenance
export const REQUEST_GET_EVENT_ITEMS = 'REQUEST_GET_EVENT_ITEMS'
export const REQUEST_GET_LOGCAT_FILE = 'REQUEST_GET_LOGCAT_FILE'
export const REQUEST_GET_TRACE_LIST = 'REQUEST_GET_TRACE_LIST'
export const REQUEST_GET_COREDUMP_LIST = 'REQUEST_GET_COREDUMP_LIST'
export const REQUEST_GET_RECORD_LIST = 'REQUEST_GET_RECORD_LIST'

// sysapp
export const REQUEST_GET_BLF = 'REQUEST_GET_BLF'
export const REQUEST_GET_NORRECORDINGLIST = 'REQUEST_GET_NORRECORDINGLIST'
// extension
