export var overviewdata = [
    {
        'name':'姓名',
        'content':'张明剑'
    },
    {
        'name':'性别',
        'content':'男'
    },
    {
        'name':'工作经验',
        'content':'2年'
    },
    {
        'name':'技能评价',
        'content':'熟悉h5的新标签的特性和语义化，css3的特效属性；'
    },
    {
        'name':'',
        'content':'熟练页面的架构和布局；'
    },
    {
        'name':'',
        'content':'熟悉原生JavaScript，es6和jquery框架和React框架；'
    },
    {
        'name':'',
        'content':'熟悉项目的性能优化。'
    },
    {
        'name':'自我描述',
        'content':'技能较为熟练，乐观开朗，适应力强。'
    }
];
export var zhiyuedata = [
    {
        'name':'工作岗位',
        'content':'暑期实习'
    },
    {
        'name':'工作时间',
        'content':'2015.7-2015.9'
    },
    {
        'name':'工作职责',
        'content':'根据UI设计师给出的设计图写出静态页面，用来供后端开发使用。'
    },
    {
        'name':'工作收获',
        'content':'css技术的提高，掌握div+css布局和响应式布局、css3属性学习'
    }
];
export var yingyingdata = [
    {
        'name':'工作岗位',
        'content':'前端实习'
    },
    {
        'name':'工作时间',
        'content':'2015.9-2016.4'
    },
    {
        'name':'工作职责',
        'content':'根据需求开发app内嵌页面，活动页；开发web网站:www.kunbofund.com'
    },
    {
        'name':'工作收获',
        'content':'掌握css动画开发，javascript的学习以及jquery的使用，移动端的适配等'
    }
];
export var grandstreamdata = [
    {
        'name':'工作岗位',
        'content':'前端开发'
    },
    {
        'name':'工作时间',
        'content':'2016.4-至今'
    },
    {
        'name':'工作职责',
        'content':'负责开发GWN项目前端模块;参与WP800，GXV项目前端开发'
    },
    {
        'name':'工作收获',
        'content':'原生js和jquery的加深，MVVM模式的研究，React框架的学习和参与；页面性能的优化'
    }
];
export var psdata = [
    {
        'name':'router旧首页',
        'src':'../../public/img/index_7000_old.png'
    },
    {
        'name':'ap旧首页',
        'src':'../../public/img/index_7610_old.png'
    },
    {
        'name':'router新首页',
        'src':'../../public/img/index_7000_new.png'
    },
    {
        'name':'ap新首页',
        'src':'../../public/img/index_7610_new.png'
    },
    {
        'name':'拖拽排序',
        'src':'../../public/img/drag.png'
    },
    {
        'name':'拖拽拉伸',
        'src':'../../public/img/pull.png'
    },
    {
        'name':'弹出编辑框',
        'src':'../../public/img/edit.png'
    },
    {
        'name':'拓扑图',
        'src':'../../public/img/mesh.png'
    },
    {
        'name':'预约界面',
        'src':'../../public/img/schedule.png'
    },
    {
        'name':'预约日期选择',
        'src':'../../public/img/schedule1.png'
    },
    {
        'name':'预约时间段选择',
        'src':'../../public/img/schedule2.png'
    },
    {
        'name':'步骤功能',
        'src':'../../public/img/setup.png'
    },
    {
        'name':'时间选择器',
        'src':'../../public/img/time.png'
    },
    {
        'name':'提示框',
        'src':'../../public/img/tooltip.png'
    }
];
